---
abstract: 'Use Data::Dump to dump data à la Steven Haryanto'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0.22
  DateTime: 0
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Dump-Ala-SHARYANTO
requires:
  Data::Dump: 1.22
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Data-Dump-Ala-SHARYANTO
  repository: http://github.com/sharyanto/perl-Data-Dump-Ala-SHARYANTO
version: 0.02
